// <auto-generated />
using System;
using Gym.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gym.Infrastructure.Migrations
{
    [DbContext(typeof(GymDbContext))]
    [Migration("20260213151841_UpdateMemberNullableUser")]
    partial class UpdateMemberNullableUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gym.Domain.Entities.CheckIn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CheckInTime");

                    b.HasIndex("MemberId");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("MemberId", "CheckInTime");

                    b.ToTable("CheckIns", (string)null);
                });

            modelBuilder.Entity("Gym.Domain.Entities.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentEnrollment")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<string>("ScheduleDay")
                        .HasColumnType("nvarchar(450)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<Guid>("TrainerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleDay")
                        .HasFilter("[IsActive] = 1");

                    b.HasIndex("TrainerId");

                    b.HasIndex("ScheduleDay", "StartTime")
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("Classes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("50505050-5050-5050-5050-505050505050"),
                            ClassName = "Yoga Buổi Sáng",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentEnrollment = 0,
                            Description = "Yoga cơ bản cho người mới bắt đầu",
                            EndTime = new TimeSpan(0, 7, 30, 0, 0),
                            IsActive = true,
                            IsDeleted = false,
                            MaxCapacity = 20,
                            ScheduleDay = "Monday",
                            StartTime = new TimeSpan(0, 6, 0, 0, 0),
                            TrainerId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("60606060-6060-6060-6060-606060606060"),
                            ClassName = "Boxing Tối",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentEnrollment = 0,
                            Description = "Boxing căn bản và nâng cao",
                            EndTime = new TimeSpan(0, 19, 30, 0, 0),
                            IsActive = true,
                            IsDeleted = false,
                            MaxCapacity = 15,
                            ScheduleDay = "Wednesday",
                            StartTime = new TimeSpan(0, 18, 0, 0, 0),
                            TrainerId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("70707070-7070-7070-7070-707070707070"),
                            ClassName = "Pilates Chiều",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentEnrollment = 0,
                            Description = "Pilates cho sức khỏe và vóc dáng",
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            IsActive = true,
                            IsDeleted = false,
                            MaxCapacity = 12,
                            ScheduleDay = "Friday",
                            StartTime = new TimeSpan(0, 16, 0, 0, 0),
                            TrainerId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        });
                });

            modelBuilder.Entity("Gym.Domain.Entities.ClassEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EnrolledDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("EnrolledDate");

                    b.HasIndex("MemberId");

                    b.HasIndex("ClassId", "MemberId")
                        .IsUnique();

                    b.ToTable("ClassEnrollments", (string)null);
                });

            modelBuilder.Entity("Gym.Domain.Entities.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmergencyContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemberCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("FullName");

                    b.HasIndex("MemberCode")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("PhoneNumber");

                    b.HasIndex("Status")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Members", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20202020-2020-2020-2020-202020202020"),
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1995, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nguyenvana@gmail.com",
                            FullName = "Nguyễn Văn A",
                            IsDeleted = false,
                            JoinedDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MemberCode = "GYM2024001",
                            PhoneNumber = "0906789012",
                            Status = 1,
                            UserId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            Id = new Guid("30303030-3030-3030-3030-303030303030"),
                            CreatedAt = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1992, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tranthib@gmail.com",
                            FullName = "Trần Thị B",
                            IsDeleted = false,
                            JoinedDate = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            MemberCode = "GYM2024002",
                            PhoneNumber = "0907890123",
                            Status = 1,
                            UserId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            Id = new Guid("40404040-4040-4040-4040-404040404040"),
                            CreatedAt = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1998, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "levanc@gmail.com",
                            FullName = "Lê Văn C",
                            IsDeleted = false,
                            JoinedDate = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            MemberCode = "GYM2024003",
                            PhoneNumber = "0908901234",
                            Status = 1,
                            UserId = new Guid("88888888-8888-8888-8888-888888888888")
                        });
                });

            modelBuilder.Entity("Gym.Domain.Entities.MemberSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("RemainingSessions")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EndDate")
                        .HasFilter("[Status] = 2");

                    b.HasIndex("MemberId");

                    b.HasIndex("PackageId");

                    b.HasIndex("Status")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("MemberId", "Status");

                    b.ToTable("MemberSubscriptions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("80808080-8080-8080-8080-808080808080"),
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateTime(2024, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MemberId = new Guid("20202020-2020-2020-2020-202020202020"),
                            PackageId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            StartDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("90909090-9090-9090-9090-909090909090"),
                            CreatedAt = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MemberId = new Guid("30303030-3030-3030-3030-303030303030"),
                            PackageId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            RemainingSessions = 10,
                            StartDate = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2
                        });
                });

            modelBuilder.Entity("Gym.Domain.Entities.MembershipPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DiscountPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DurationInDays")
                        .HasColumnType("int");

                    b.Property<int>("DurationInMonths")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SessionLimit")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("MembershipPackages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Truy cập phòng gym không giới hạn trong 30 ngày",
                            DurationInDays = 30,
                            DurationInMonths = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Gói Cơ Bản 1 Tháng",
                            Price = 500000m
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gym + Tất cả lớp học trong 30 ngày",
                            DiscountPrice = 750000m,
                            DurationInDays = 30,
                            DurationInMonths = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Gói Premium 1 Tháng",
                            Price = 800000m
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "10 buổi tập, hạn sử dụng 60 ngày",
                            DurationInDays = 60,
                            DurationInMonths = 2,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Gói 10 Buổi Tập",
                            Price = 450000m,
                            SessionLimit = 10
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Truy cập không giới hạn 90 ngày",
                            DiscountPrice = 1100000m,
                            DurationInDays = 90,
                            DurationInMonths = 3,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Gói 3 Tháng",
                            Price = 1200000m
                        },
                        new
                        {
                            Id = new Guid("10101010-1010-1010-1010-101010101010"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Toàn bộ dịch vụ + PT cá nhân trong 365 ngày",
                            DiscountPrice = 4000000m,
                            DurationInDays = 365,
                            DurationInMonths = 12,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Gói VIP 1 Năm",
                            Price = 4500000m
                        });
                });

            modelBuilder.Entity("Gym.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("MemberSubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Method")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MemberSubscriptionId");

                    b.HasIndex("PaymentDate");

                    b.HasIndex("Status");

                    b.HasIndex("TransactionId")
                        .HasFilter("[TransactionId] IS NOT NULL");

                    b.ToTable("Payments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1a1a1a1-a1a1-a1a1-a1a1-a1a1a1a1a1a1"),
                            Amount = 750000m,
                            CreatedAt = new DateTime(2024, 2, 1, 10, 30, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            MemberSubscriptionId = new Guid("80808080-8080-8080-8080-808080808080"),
                            Method = 3,
                            Note = "Thanh toán gói Premium 1 tháng",
                            PaymentDate = new DateTime(2024, 2, 1, 10, 30, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            TransactionId = "TXN20240201001"
                        },
                        new
                        {
                            Id = new Guid("b2b2b2b2-b2b2-b2b2-b2b2-b2b2b2b2b2b2"),
                            Amount = 450000m,
                            CreatedAt = new DateTime(2024, 2, 5, 14, 15, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            MemberSubscriptionId = new Guid("90909090-9090-9090-9090-909090909090"),
                            Method = 1,
                            Note = "Thanh toán gói 10 buổi tập",
                            PaymentDate = new DateTime(2024, 2, 5, 14, 15, 0, 0, DateTimeKind.Utc),
                            Status = 2
                        });
                });

            modelBuilder.Entity("Gym.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Permissions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Full system access",
                            Permissions = "[\"*\"]",
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manage gym operations",
                            Permissions = "[\"members.*\", \"packages.*\", \"subscriptions.*\", \"payments.*\", \"checkins.*\", \"reports.*\"]",
                            RoleName = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manage classes and view members",
                            Permissions = "[\"classes.*\", \"members.view\", \"checkins.view\"]",
                            RoleName = "Trainer"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Check-in and basic operations",
                            Permissions = "[\"checkins.*\", \"members.view\", \"subscriptions.view\"]",
                            RoleName = "Receptionist"
                        });
                });

            modelBuilder.Entity("Gym.Domain.Entities.Trainer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePhoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("IsActive")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Trainers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Bio = "HLV Yoga với 8 năm kinh nghiệm, chứng chỉ quốc tế RYT-500",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "trainer1@gym.com",
                            FullName = "Trần Thị Hương",
                            HireDate = new DateTime(2020, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            PhoneNumber = "0903456789",
                            Specialization = "Yoga, Pilates, Meditation",
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Bio = "Võ sư Boxing chuyên nghiệp, từng thi đấu SEA Games",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "trainer2@gym.com",
                            FullName = "Lê Văn Nam",
                            HireDate = new DateTime(2021, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            PhoneNumber = "0904567890",
                            Specialization = "Boxing, Muay Thai, CrossFit",
                            UserId = new Guid("44444444-4444-4444-4444-444444444444")
                        });
                });

            modelBuilder.Entity("Gym.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@gym.com",
                            FullName = "System Administrator",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEOsQ7h6lKcpUIhjoBSoj71Q700WAlwWUlh3rWlCxs3yST+ah2FtN9W/18oR5WBkvZA==",
                            PhoneNumber = "0901234567",
                            RoleId = 1,
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "manager@gym.com",
                            FullName = "Nguyễn Văn Manager",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEGbs6ae9gvjxjBmqFCarwnEZOU9lmuGffC5WiaLrPxnXxKM1NG0ClgLFlyOMb6oCuA==",
                            PhoneNumber = "0902345678",
                            RoleId = 2,
                            Username = "manager"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "trainer1@gym.com",
                            FullName = "Trần Thị Hương",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEI1+k+tDg0XAWxHckkpDDmr8lHZTLJFxN4qxKaPhwEz0oMd8qtGvXkqZiFtKxvR4fQ==",
                            PhoneNumber = "0903456789",
                            RoleId = 3,
                            Username = "trainer1"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "trainer2@gym.com",
                            FullName = "Lê Văn Nam",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEBlmdkk6vM308KIeMYMEO1BoHBSOdtZPyR9osX5zg+MJBZWDlttwlsyU9LXCisMwtg==",
                            PhoneNumber = "0904567890",
                            RoleId = 3,
                            Username = "trainer2"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "receptionist@gym.com",
                            FullName = "Phạm Thị Lan",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEFqUFKuGPsmF5jL7Q8ojqR6f6+30aJCW8hSpD7mMLsXZ1wLPpeHudQQUDcl3xaWZ0w==",
                            PhoneNumber = "0905678901",
                            RoleId = 4,
                            Username = "receptionist"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nguyenvana@gmail.com",
                            FullName = "Nguyễn Văn A",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEN9rnOOnqmXNh9J49FpQJreQplYshbo7GVyPxnT+Irt0vFF095dTo0SLSZuiz+LWqw==",
                            PhoneNumber = "0906789012",
                            RoleId = 4,
                            Username = "member001"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            CreatedAt = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "tranthib@gmail.com",
                            FullName = "Trần Thị B",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEMwr9RGDFuqMQ/zffuvY3WXnPOEzPLvyta5b+3zj0Iu3VCVbWNRQb44iaguOGzVv/w==",
                            PhoneNumber = "0907890123",
                            RoleId = 4,
                            Username = "member002"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            CreatedAt = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "levanc@gmail.com",
                            FullName = "Lê Văn C",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEA6SHbvqdlXWXLxPzoNYZR/1Z87+P1gI3/GXV1B3NoWN+9JlL9mUB6tb8MernQJgWA==",
                            PhoneNumber = "0908901234",
                            RoleId = 4,
                            Username = "member003"
                        });
                });

            modelBuilder.Entity("Gym.Domain.Entities.CheckIn", b =>
                {
                    b.HasOne("Gym.Domain.Entities.Member", "Member")
                        .WithMany("CheckIns")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gym.Domain.Entities.MemberSubscription", "Subscription")
                        .WithMany("CheckIns")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Member");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Gym.Domain.Entities.Class", b =>
                {
                    b.HasOne("Gym.Domain.Entities.Trainer", "Trainer")
                        .WithMany("Classes")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("Gym.Domain.Entities.ClassEnrollment", b =>
                {
                    b.HasOne("Gym.Domain.Entities.Class", "Class")
                        .WithMany("ClassEnrollments")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gym.Domain.Entities.Member", "Member")
                        .WithMany("ClassEnrollments")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Gym.Domain.Entities.Member", b =>
                {
                    b.HasOne("Gym.Domain.Entities.User", "User")
                        .WithOne("Member")
                        .HasForeignKey("Gym.Domain.Entities.Member", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gym.Domain.Entities.MemberSubscription", b =>
                {
                    b.HasOne("Gym.Domain.Entities.Member", "Member")
                        .WithMany("Subscriptions")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gym.Domain.Entities.MembershipPackage", "Package")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Gym.Domain.Entities.Payment", b =>
                {
                    b.HasOne("Gym.Domain.Entities.MemberSubscription", "Subscription")
                        .WithMany("Payments")
                        .HasForeignKey("MemberSubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Gym.Domain.Entities.Trainer", b =>
                {
                    b.HasOne("Gym.Domain.Entities.User", "User")
                        .WithOne("Trainer")
                        .HasForeignKey("Gym.Domain.Entities.Trainer", "UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gym.Domain.Entities.User", b =>
                {
                    b.HasOne("Gym.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Gym.Domain.Entities.Class", b =>
                {
                    b.Navigation("ClassEnrollments");
                });

            modelBuilder.Entity("Gym.Domain.Entities.Member", b =>
                {
                    b.Navigation("CheckIns");

                    b.Navigation("ClassEnrollments");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Gym.Domain.Entities.MemberSubscription", b =>
                {
                    b.Navigation("CheckIns");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Gym.Domain.Entities.MembershipPackage", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Gym.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Gym.Domain.Entities.Trainer", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("Gym.Domain.Entities.User", b =>
                {
                    b.Navigation("Member");

                    b.Navigation("Trainer");
                });
#pragma warning restore 612, 618
        }
    }
}
